// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealmEngine.Data.Persistence;

#nullable disable

namespace RealmEngine.Data.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260315023458_ActorArchitectureRefactor")]
    partial class ActorArchitectureRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealmEngine.Data.Entities.Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorArchetype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClassId");

                    b.HasIndex("LootTableId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("ActorArchetypes");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryStat")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("ActorClasses");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchetypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FactionOverride")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LevelOverride")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LootTableOverride")
                        .HasColumnType("uuid");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchetypeId");

                    b.HasIndex("LootTableOverride");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("ActorInstances");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ArchetypeAbilityPool", b =>
                {
                    b.Property<Guid>("ArchetypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.Property<float>("UseChance")
                        .HasColumnType("real");

                    b.HasKey("ArchetypeId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("ArchetypeAbilityPools");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Armor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArmorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EquipSlot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ClassAbilityUnlock", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.HasKey("ClassId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("ClassAbilityUnlocks");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ContentRegistry", b =>
                {
                    b.Property<string>("Domain")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TypeKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Domain", "TypeKey", "Slug");

                    b.HasIndex("EntityId");

                    b.ToTable("ContentRegistry");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Dialogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Speaker")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Enchantment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TargetSlot")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Enchantments");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.GameConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ConfigKey");

                    b.ToTable("GameConfigs");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.InstanceAbilityPool", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.HasKey("InstanceId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("InstanceAbilityPools");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("LootTables");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DropWeight")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGuaranteed")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemDomain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityMax")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.ToTable("LootTableEntries");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CostScale")
                        .HasColumnType("real");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.MaterialProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("CostScale")
                        .HasColumnType("real");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("MaterialProperties");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NameComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "ComponentKey", "Value")
                        .IsUnique();

                    b.ToTable("NameComponents");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NamePattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("NamePatterns");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NamePatternSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EntityPath")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("SupportsTraits")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityPath")
                        .IsUnique();

                    b.ToTable("NamePatternSets");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CraftingLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CraftingSkill")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OutputItemDomain")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OutputItemSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemDomain")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemSlug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "ItemDomain", "ItemSlug");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRank")
                        .HasColumnType("integer");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.SpeciesAbilityPool", b =>
                {
                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.HasKey("SpeciesId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("SpeciesAbilityPools");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.TraitDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AppliesTo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Key");

                    b.ToTable("TraitDefinitions");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("HandsRequired")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.WorldLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RarityWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TypeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeKey");

                    b.HasIndex("TypeKey", "Slug")
                        .IsUnique();

                    b.ToTable("WorldLocations");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Ability", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.AbilityEffects", "Effects", b1 =>
                        {
                            b1.Property<Guid>("AbilityId");

                            b1.Property<string>("BuffApplied");

                            b1.Property<string>("ConditionApplied");

                            b1.Property<float?>("ConditionChance");

                            b1.Property<string>("DamageType");

                            b1.Property<string>("DebuffApplied");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.ToJson("Effects");

                            b1.WithOwner()
                                .HasForeignKey("AbilityId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.AbilityStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("AbilityId");

                            b1.Property<float?>("CastTime");

                            b1.Property<float?>("Cooldown");

                            b1.Property<int?>("DamageMax");

                            b1.Property<int?>("DamageMin");

                            b1.Property<float?>("Duration");

                            b1.Property<int?>("HealMax");

                            b1.Property<int?>("HealMin");

                            b1.Property<int?>("ManaCost");

                            b1.Property<int?>("MaxTargets");

                            b1.Property<int?>("Radius");

                            b1.Property<float?>("Range");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("AbilityId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.AbilityTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("AbilityId");

                            b1.Property<bool?>("CanCrit");

                            b1.Property<bool?>("HasCooldown");

                            b1.Property<bool?>("IsAoe");

                            b1.Property<bool?>("IsChanneled");

                            b1.Property<bool?>("IsInstant");

                            b1.Property<bool?>("IsPassive");

                            b1.Property<bool?>("RequiresTarget");

                            b1.Property<bool?>("RequiresWeapon");

                            b1.HasKey("AbilityId");

                            b1.ToTable("Abilities");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("AbilityId");
                        });

                    b.Navigation("Effects")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorArchetype", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealmEngine.Data.Entities.ActorClass", "Class")
                        .WithMany("Archetypes")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealmEngine.Data.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealmEngine.Data.Entities.Species", "Species")
                        .WithMany("Archetypes")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("RealmEngine.Data.Entities.ArchetypeStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ActorArchetypeId");

                            b1.Property<int?>("Agility");

                            b1.Property<int?>("ArmorClass");

                            b1.Property<int?>("AttackBonus");

                            b1.Property<int?>("Constitution");

                            b1.Property<int?>("Damage");

                            b1.Property<int?>("ExperienceReward");

                            b1.Property<int?>("GoldRewardMax");

                            b1.Property<int?>("GoldRewardMin");

                            b1.Property<int?>("Health");

                            b1.Property<int?>("Intelligence");

                            b1.Property<int?>("Mana");

                            b1.Property<int?>("Strength");

                            b1.Property<int?>("TradeGold");

                            b1.Property<int?>("TradeSkill");

                            b1.HasKey("ActorArchetypeId");

                            b1.ToTable("ActorArchetypes");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("ActorArchetypeId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.ArchetypeTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("ActorArchetypeId");

                            b1.Property<bool?>("Aggressive");

                            b1.Property<bool?>("Boss");

                            b1.Property<bool?>("Caster");

                            b1.Property<bool?>("ColdImmune");

                            b1.Property<bool?>("Elite");

                            b1.Property<bool?>("FireImmune");

                            b1.Property<bool?>("HasDialogue");

                            b1.Property<bool?>("Hostile");

                            b1.Property<bool?>("Immortal");

                            b1.Property<bool?>("PackHunter");

                            b1.Property<bool?>("PoisonImmune");

                            b1.Property<bool?>("QuestGiver");

                            b1.Property<bool?>("Ranged");

                            b1.Property<bool?>("Shopkeeper");

                            b1.Property<bool?>("Wanderer");

                            b1.HasKey("ActorArchetypeId");

                            b1.ToTable("ActorArchetypes");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("ActorArchetypeId");
                        });

                    b.Navigation("Background");

                    b.Navigation("Class");

                    b.Navigation("LootTable");

                    b.Navigation("Species");

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorClass", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.ActorClassStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ActorClassId");

                            b1.Property<int?>("BaseHealth");

                            b1.Property<int?>("BaseMana");

                            b1.Property<float?>("ConstitutionGrowth");

                            b1.Property<float?>("DexterityGrowth");

                            b1.Property<float?>("HealthGrowth");

                            b1.Property<float?>("IntelligenceGrowth");

                            b1.Property<float?>("ManaGrowth");

                            b1.Property<float?>("StrengthGrowth");

                            b1.HasKey("ActorClassId");

                            b1.ToTable("ActorClasses");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("ActorClassId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.ActorClassTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("ActorClassId");

                            b1.Property<bool?>("CanDualWield");

                            b1.Property<bool?>("CanWearHeavy");

                            b1.Property<bool?>("CanWearShield");

                            b1.Property<bool?>("Melee");

                            b1.Property<bool?>("Ranged");

                            b1.Property<bool?>("Spellcaster");

                            b1.Property<bool?>("Stealth");

                            b1.HasKey("ActorClassId");

                            b1.ToTable("ActorClasses");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("ActorClassId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorInstance", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.ActorArchetype", "Archetype")
                        .WithMany("Instances")
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmEngine.Data.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableOverride")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("RealmEngine.Data.Entities.InstanceStatOverrides", "StatOverrides", b1 =>
                        {
                            b1.Property<Guid>("ActorInstanceId");

                            b1.Property<int?>("Agility");

                            b1.Property<int?>("ArmorClass");

                            b1.Property<int?>("AttackBonus");

                            b1.Property<int?>("Constitution");

                            b1.Property<int?>("Damage");

                            b1.Property<int?>("ExperienceReward");

                            b1.Property<int?>("GoldRewardMax");

                            b1.Property<int?>("GoldRewardMin");

                            b1.Property<int?>("Health");

                            b1.Property<int?>("Intelligence");

                            b1.Property<int?>("Mana");

                            b1.Property<int?>("Strength");

                            b1.HasKey("ActorInstanceId");

                            b1.ToTable("ActorInstances");

                            b1.ToJson("StatOverrides");

                            b1.WithOwner()
                                .HasForeignKey("ActorInstanceId");
                        });

                    b.Navigation("Archetype");

                    b.Navigation("LootTable");

                    b.Navigation("StatOverrides")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ArchetypeAbilityPool", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Ability", "Ability")
                        .WithMany("ArchetypePool")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmEngine.Data.Entities.ActorArchetype", "Archetype")
                        .WithMany("AbilityPool")
                        .HasForeignKey("ArchetypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Archetype");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Armor", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.ArmorStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ArmorId");

                            b1.Property<int?>("ArmorRating");

                            b1.Property<int?>("Durability");

                            b1.Property<int?>("MagicResist");

                            b1.Property<float?>("MovementPenalty");

                            b1.Property<int?>("Value");

                            b1.Property<float?>("Weight");

                            b1.HasKey("ArmorId");

                            b1.ToTable("Armors");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("ArmorId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.ArmorTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("ArmorId");

                            b1.Property<bool?>("ColdResist");

                            b1.Property<bool?>("Cursed");

                            b1.Property<bool?>("FireResist");

                            b1.Property<bool?>("LightningResist");

                            b1.Property<bool?>("Magical");

                            b1.Property<bool?>("StealthPenalty");

                            b1.HasKey("ArmorId");

                            b1.ToTable("Armors");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("ArmorId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Background", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.BackgroundStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("BackgroundId");

                            b1.Property<int?>("BonusConstitution");

                            b1.Property<int?>("BonusDexterity");

                            b1.Property<int?>("BonusIntelligence");

                            b1.Property<int?>("BonusStrength");

                            b1.Property<int?>("SkillBonusValue");

                            b1.Property<int?>("StartingGold");

                            b1.Property<string>("StartingSkillBonus");

                            b1.HasKey("BackgroundId");

                            b1.ToTable("Backgrounds");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("BackgroundId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.BackgroundTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("BackgroundId");

                            b1.Property<bool?>("Criminal");

                            b1.Property<bool?>("Merchant");

                            b1.Property<bool?>("Military");

                            b1.Property<bool?>("Noble");

                            b1.Property<bool?>("Regional");

                            b1.Property<bool?>("Religious");

                            b1.Property<bool?>("Scholar");

                            b1.HasKey("BackgroundId");

                            b1.ToTable("Backgrounds");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("BackgroundId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ClassAbilityUnlock", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Ability", "Ability")
                        .WithMany("ClassUnlocks")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmEngine.Data.Entities.ActorClass", "Class")
                        .WithMany("AbilityUnlocks")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Dialogue", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.DialogueStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("DialogueId");

                            b1.Property<int?>("Formality");

                            b1.PrimitiveCollection<string>("Lines")
                                .IsRequired();

                            b1.Property<int?>("Tone");

                            b1.HasKey("DialogueId");

                            b1.ToTable("Dialogues");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("DialogueId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.DialogueTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("DialogueId");

                            b1.Property<bool?>("Farewell");

                            b1.Property<bool?>("Friendly");

                            b1.Property<bool?>("Greeting");

                            b1.Property<bool?>("Hostile");

                            b1.Property<bool?>("Merchant");

                            b1.Property<bool?>("QuestRelated");

                            b1.HasKey("DialogueId");

                            b1.ToTable("Dialogues");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("DialogueId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Enchantment", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.EnchantmentStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("EnchantmentId");

                            b1.Property<float?>("AttackSpeedBonus");

                            b1.Property<int?>("BonusArmor");

                            b1.Property<int?>("BonusDamage");

                            b1.Property<int?>("BonusDexterity");

                            b1.Property<int?>("BonusIntelligence");

                            b1.Property<int?>("BonusStrength");

                            b1.Property<float?>("ManaCostReduction");

                            b1.Property<int?>("Value");

                            b1.HasKey("EnchantmentId");

                            b1.ToTable("Enchantments");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("EnchantmentId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.EnchantmentTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("EnchantmentId");

                            b1.Property<bool?>("Cursed");

                            b1.Property<bool?>("Exclusive");

                            b1.Property<bool?>("Permanent");

                            b1.Property<bool?>("RequiresMagicItem");

                            b1.Property<bool?>("Stackable");

                            b1.HasKey("EnchantmentId");

                            b1.ToTable("Enchantments");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("EnchantmentId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.InstanceAbilityPool", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Ability", "Ability")
                        .WithMany("InstancePool")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmEngine.Data.Entities.ActorInstance", "Instance")
                        .WithMany("AbilityPool")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Item", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.ItemStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ItemId");

                            b1.Property<float?>("Duration");

                            b1.Property<float?>("EffectPower");

                            b1.Property<int?>("StackSize");

                            b1.Property<int?>("Value");

                            b1.Property<float?>("Weight");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.ItemTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("ItemId");

                            b1.Property<bool?>("Consumable");

                            b1.Property<bool?>("Magical");

                            b1.Property<bool?>("QuestItem");

                            b1.Property<bool?>("Soulbound");

                            b1.Property<bool?>("Stackable");

                            b1.Property<bool?>("Unique");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.LootTable", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.LootTableTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("LootTableId");

                            b1.Property<bool?>("Boss");

                            b1.Property<bool?>("Common");

                            b1.Property<bool?>("Elite");

                            b1.Property<bool?>("IsChest");

                            b1.Property<bool?>("IsHarvesting");

                            b1.Property<bool?>("Rare");

                            b1.HasKey("LootTableId");

                            b1.ToTable("LootTables");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("LootTableId");
                        });

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.LootTableEntry", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.LootTable", "LootTable")
                        .WithMany("Entries")
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootTable");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Material", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.MaterialStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("MaterialId");

                            b1.Property<float?>("Conductivity");

                            b1.Property<float?>("Hardness");

                            b1.Property<float?>("MagicAffinity");

                            b1.Property<int?>("Value");

                            b1.Property<float?>("Weight");

                            b1.HasKey("MaterialId");

                            b1.ToTable("Materials");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.MaterialTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("MaterialId");

                            b1.Property<bool?>("Brittle");

                            b1.Property<bool?>("Conductive");

                            b1.Property<bool?>("Enchantable");

                            b1.Property<bool?>("FireResist");

                            b1.Property<bool?>("Flexible");

                            b1.Property<bool?>("Magical");

                            b1.HasKey("MaterialId");

                            b1.ToTable("Materials");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("MaterialId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.MaterialProperty", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.MaterialPropertyStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("MaterialPropertyId");

                            b1.Property<float?>("Conductivity");

                            b1.Property<float?>("Durability");

                            b1.Property<float?>("Hardness");

                            b1.Property<float?>("MagicAffinity");

                            b1.Property<int?>("Value");

                            b1.Property<float?>("Weight");

                            b1.HasKey("MaterialPropertyId");

                            b1.ToTable("MaterialProperties");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("MaterialPropertyId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.MaterialPropertyTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("MaterialPropertyId");

                            b1.Property<bool?>("Brittle");

                            b1.Property<bool?>("Conducting");

                            b1.Property<bool?>("Enchantable");

                            b1.Property<bool?>("Fireproof");

                            b1.Property<bool?>("Flexible");

                            b1.Property<bool?>("Magical");

                            b1.Property<bool?>("Transparent");

                            b1.HasKey("MaterialPropertyId");

                            b1.ToTable("MaterialProperties");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("MaterialPropertyId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NameComponent", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.NamePatternSet", "Set")
                        .WithMany("Components")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NamePattern", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.NamePatternSet", "Set")
                        .WithMany("Patterns")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Set");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Organization", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.OrganizationStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId");

                            b1.Property<int?>("MemberCount");

                            b1.Property<int?>("ReputationThresholdFriendly");

                            b1.Property<int?>("ReputationThresholdHostile");

                            b1.Property<int?>("Wealth");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.OrganizationTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId");

                            b1.Property<bool?>("HasShop");

                            b1.Property<bool?>("Hostile");

                            b1.Property<bool?>("Joinable");

                            b1.Property<bool?>("PoliticalFaction");

                            b1.Property<bool?>("QuestGiver");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Quest", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.QuestObjectives", "Objectives", b1 =>
                        {
                            b1.Property<Guid>("QuestId");

                            b1.HasKey("QuestId");

                            b1.ToTable("Quests");

                            b1.ToJson("Objectives");

                            b1.WithOwner()
                                .HasForeignKey("QuestId");

                            b1.OwnsMany("RealmEngine.Data.Entities.QuestObjective", "Items", b2 =>
                                {
                                    b2.Property<Guid>("QuestObjectivesQuestId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Description");

                                    b2.Property<int>("Quantity");

                                    b2.Property<string>("Target")
                                        .IsRequired();

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("QuestObjectivesQuestId", "__synthesizedOrdinal");

                                    b2.ToTable("Quests");

                                    b2.WithOwner()
                                        .HasForeignKey("QuestObjectivesQuestId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.QuestRewards", "Rewards", b1 =>
                        {
                            b1.Property<Guid>("QuestId");

                            b1.HasKey("QuestId");

                            b1.ToTable("Quests");

                            b1.ToJson("Rewards");

                            b1.WithOwner()
                                .HasForeignKey("QuestId");

                            b1.OwnsMany("RealmEngine.Data.Entities.QuestReward", "Items", b2 =>
                                {
                                    b2.Property<Guid>("QuestRewardsQuestId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int?>("Amount");

                                    b2.Property<string>("ItemDomain");

                                    b2.Property<string>("ItemSlug");

                                    b2.Property<int?>("Quantity");

                                    b2.Property<string>("Type")
                                        .IsRequired();

                                    b2.HasKey("QuestRewardsQuestId", "__synthesizedOrdinal");

                                    b2.ToTable("Quests");

                                    b2.WithOwner()
                                        .HasForeignKey("QuestRewardsQuestId");
                                });

                            b1.Navigation("Items");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.QuestStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("QuestId");

                            b1.Property<int?>("GoldReward");

                            b1.Property<int?>("ReputationReward");

                            b1.Property<int?>("XpReward");

                            b1.HasKey("QuestId");

                            b1.ToTable("Quests");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("QuestId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.QuestTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("QuestId");

                            b1.Property<bool?>("GroupQuest");

                            b1.Property<bool?>("HiddenUntilDiscovered");

                            b1.Property<bool?>("MainStory");

                            b1.Property<bool?>("Repeatable");

                            b1.Property<bool?>("Timed");

                            b1.HasKey("QuestId");

                            b1.ToTable("Quests");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("QuestId");
                        });

                    b.Navigation("Objectives")
                        .IsRequired();

                    b.Navigation("Rewards")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Recipe", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.RecipeTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("RecipeId");

                            b1.Property<bool?>("Discoverable");

                            b1.Property<bool?>("IsAlchemy");

                            b1.Property<bool?>("IsBlacksmithing");

                            b1.Property<bool?>("IsLeatherworking");

                            b1.Property<bool?>("RequiresFire");

                            b1.Property<bool?>("RequiresStation");

                            b1.HasKey("RecipeId");

                            b1.ToTable("Recipes");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Skill", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.SkillStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("SkillId");

                            b1.Property<int?>("BaseValue");

                            b1.Property<float?>("BonusPerRank");

                            b1.Property<int?>("XpPerRank");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.SkillTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("SkillId");

                            b1.Property<bool?>("Combat");

                            b1.Property<bool?>("Crafting");

                            b1.Property<bool?>("Exploration");

                            b1.Property<bool?>("Passive");

                            b1.Property<bool?>("Social");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Species", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.SpeciesStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("SpeciesId");

                            b1.Property<int?>("BaseAgility");

                            b1.Property<int?>("BaseConstitution");

                            b1.Property<int?>("BaseHealth");

                            b1.Property<int?>("BaseIntelligence");

                            b1.Property<int?>("BaseStrength");

                            b1.Property<float?>("MovementSpeed");

                            b1.Property<int?>("NaturalArmor");

                            b1.Property<string>("SizeCategory");

                            b1.HasKey("SpeciesId");

                            b1.ToTable("Species");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.SpeciesTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("SpeciesId");

                            b1.Property<bool?>("Aquatic");

                            b1.Property<bool?>("Beast");

                            b1.Property<bool?>("Construct");

                            b1.Property<bool?>("Darkvision");

                            b1.Property<bool?>("Demon");

                            b1.Property<bool?>("Dragon");

                            b1.Property<bool?>("Elemental");

                            b1.Property<bool?>("Flying");

                            b1.Property<bool?>("Humanoid");

                            b1.Property<bool?>("Undead");

                            b1.HasKey("SpeciesId");

                            b1.ToTable("Species");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("SpeciesId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.SpeciesAbilityPool", b =>
                {
                    b.HasOne("RealmEngine.Data.Entities.Ability", "Ability")
                        .WithMany("SpeciesPool")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmEngine.Data.Entities.Species", "Species")
                        .WithMany("AbilityPool")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Spell", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.SpellStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("SpellId");

                            b1.Property<float?>("CastTime");

                            b1.Property<float?>("Cooldown");

                            b1.Property<int?>("DamageMax");

                            b1.Property<int?>("DamageMin");

                            b1.Property<float?>("Duration");

                            b1.Property<int?>("HealMax");

                            b1.Property<int?>("HealMin");

                            b1.Property<int?>("ManaCost");

                            b1.Property<float?>("Range");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.SpellTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("SpellId");

                            b1.Property<bool?>("CanCrit");

                            b1.Property<bool?>("Instant");

                            b1.Property<bool?>("IsAoe");

                            b1.Property<bool?>("IsChanneled");

                            b1.Property<bool?>("RequiresConcentration");

                            b1.Property<bool?>("RequiresStaff");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Weapon", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.WeaponStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("WeaponId");

                            b1.Property<float?>("AttackSpeed");

                            b1.Property<float?>("CritChance");

                            b1.Property<int?>("DamageMax");

                            b1.Property<int?>("DamageMin");

                            b1.Property<int?>("Durability");

                            b1.Property<float?>("Range");

                            b1.Property<int?>("Value");

                            b1.Property<float?>("Weight");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Weapons");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.WeaponTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("WeaponId");

                            b1.Property<bool?>("Finesse");

                            b1.Property<bool?>("Magical");

                            b1.Property<bool?>("Reach");

                            b1.Property<bool?>("Silvered");

                            b1.Property<bool?>("Throwable");

                            b1.Property<bool?>("TwoHanded");

                            b1.Property<bool?>("Versatile");

                            b1.HasKey("WeaponId");

                            b1.ToTable("Weapons");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("WeaponId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.WorldLocation", b =>
                {
                    b.OwnsOne("RealmEngine.Data.Entities.WorldLocationStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("WorldLocationId");

                            b1.Property<int?>("DangerLevel");

                            b1.Property<int?>("MaxLevel");

                            b1.Property<int?>("MinLevel");

                            b1.Property<int?>("Population");

                            b1.Property<int?>("Size");

                            b1.HasKey("WorldLocationId");

                            b1.ToTable("WorldLocations");

                            b1.ToJson("Stats");

                            b1.WithOwner()
                                .HasForeignKey("WorldLocationId");
                        });

                    b.OwnsOne("RealmEngine.Data.Entities.WorldLocationTraits", "Traits", b1 =>
                        {
                            b1.Property<Guid>("WorldLocationId");

                            b1.Property<bool?>("HasMerchant");

                            b1.Property<bool?>("IsDiscoverable");

                            b1.Property<bool?>("IsDungeon");

                            b1.Property<bool?>("IsIndoor");

                            b1.Property<bool?>("IsTown");

                            b1.Property<bool?>("PvpEnabled");

                            b1.HasKey("WorldLocationId");

                            b1.ToTable("WorldLocations");

                            b1.ToJson("Traits");

                            b1.WithOwner()
                                .HasForeignKey("WorldLocationId");
                        });

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("Traits")
                        .IsRequired();
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Ability", b =>
                {
                    b.Navigation("ArchetypePool");

                    b.Navigation("ClassUnlocks");

                    b.Navigation("InstancePool");

                    b.Navigation("SpeciesPool");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorArchetype", b =>
                {
                    b.Navigation("AbilityPool");

                    b.Navigation("Instances");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorClass", b =>
                {
                    b.Navigation("AbilityUnlocks");

                    b.Navigation("Archetypes");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.ActorInstance", b =>
                {
                    b.Navigation("AbilityPool");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.LootTable", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.NamePatternSet", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Patterns");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("RealmEngine.Data.Entities.Species", b =>
                {
                    b.Navigation("AbilityPool");

                    b.Navigation("Archetypes");
                });
#pragma warning restore 612, 618
        }
    }
}
