using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealmEngine.Data.Entities;
using RealmUnbound.Server.Data.Entities;

namespace RealmUnbound.Server.Data;

/// <summary>
/// Primary EF Core context for all server-side persistence.
/// Inherits ASP.NET Core Identity tables (AspNetUsers, AspNetRoles, etc.) via
/// <see cref="IdentityDbContext{TUser,TRole,TKey}"/>.
/// Always backed by PostgreSQL; use <see cref="ContentDbContext"/> for standalone
/// content-browsing tools (e.g. RealmForge) that don't need Identity.
/// </summary>
public class ApplicationDbContext : IdentityDbContext<PlayerAccount, IdentityRole<Guid>, Guid>
{
    /// <summary>Initializes a new instance of <see cref="ApplicationDbContext"/>.</summary>
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

    /// <summary>Game characters owned by player accounts.</summary>
    public DbSet<Entities.Character> Characters => Set<Entities.Character>();
    /// <summary>Zone locations that characters have unlocked through discovery or quests.</summary>
    public DbSet<CharacterUnlockedLocation> CharacterUnlockedLocations => Set<CharacterUnlockedLocation>();
    /// <summary>JWT refresh tokens.</summary>
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    /// <summary>Top-level world containers (currently only Draveth).</summary>
    public DbSet<World> Worlds => Set<World>();
    /// <summary>Geographic regions within a world.</summary>
    public DbSet<Region> Regions => Set<Region>();
    /// <summary>Directed travel edges between adjacent regions.</summary>
    public DbSet<RegionConnection> RegionConnections => Set<RegionConnection>();
    /// <summary>Zone catalog — static and procedurally generated areas.</summary>
    public DbSet<Zone> Zones => Set<Zone>();
    /// <summary>Live records of characters currently in the world (on a region map or inside a zone).</summary>
    public DbSet<PlayerSession> PlayerSessions => Set<PlayerSession>();
    /// <summary>Community content submissions for the Foundry portal.</summary>
    public DbSet<FoundrySubmission> FoundrySubmissions => Set<FoundrySubmission>();
    /// <summary>User votes on Foundry submissions.</summary>
    public DbSet<FoundryVote> FoundryVotes => Set<FoundryVote>();
    /// <summary>User notifications generated by Foundry review events.</summary>
    public DbSet<FoundryNotification> FoundryNotifications => Set<FoundryNotification>();
    /// <summary>News and system announcements displayed in the client news panel.</summary>
    public DbSet<Announcement> Announcements => Set<Announcement>();
    /// <summary>Server-wide key/value counters (e.g. global rescue fund total).</summary>
    public DbSet<GlobalStat> GlobalStats => Set<GlobalStat>();
    /// <summary>Immutable audit trail of all moderation and administrative actions.</summary>
    public DbSet<AdminAuditEntry> AdminAuditEntries => Set<AdminAuditEntry>();
    /// <summary>Player-submitted reports about other players' behaviour.</summary>
    public DbSet<PlayerReport> PlayerReports => Set<PlayerReport>();
    /// <summary>Pending OAuth provider-link confirmation tokens. Consumed once via <c>GET /api/auth/link/confirm</c>.</summary>
    public DbSet<PendingLinkToken> PendingLinkTokens => Set<PendingLinkToken>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder); // required — scaffolds all Identity tables

        builder.Entity<Entities.Character>(e =>
        {
            e.HasKey(c => c.Id);
            // Character names are globally unique across the server.
            e.HasIndex(c => c.Name).IsUnique();
            // A single account cannot have two characters in the same slot.
            e.HasIndex(c => new { c.AccountId, c.SlotIndex }).IsUnique();
            e.Property(c => c.Attributes).HasColumnType("text");
            e.Property(c => c.EquipmentBlob).HasColumnType("text").HasDefaultValue("{}");
            e.Property(c => c.DifficultyMode).HasMaxLength(16).HasDefaultValue("normal");
            e.Property(c => c.TileZoneId).HasMaxLength(64).IsRequired(false);
            e.HasOne(c => c.Account)
             .WithMany()
             .HasForeignKey(c => c.AccountId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<CharacterUnlockedLocation>(e =>
        {
            e.HasKey(u => u.Id);
            // One row per character-location combination.
            e.HasIndex(u => new { u.CharacterId, u.LocationSlug }).IsUnique();
            e.Property(u => u.LocationSlug).HasMaxLength(128).IsRequired();
            e.Property(u => u.UnlockSource).HasMaxLength(64).IsRequired();
            e.HasOne(u => u.Character)
             .WithMany()
             .HasForeignKey(u => u.CharacterId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<RefreshToken>(e =>
        {
            e.HasKey(rt => rt.Id);
            e.HasIndex(rt => rt.TokenHash).IsUnique();
            e.HasOne(rt => rt.Account)
             .WithMany()
             .HasForeignKey(rt => rt.AccountId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<PendingLinkToken>(e =>
        {
            e.HasKey(t => t.Id);
            // Token hash must be unique — only one active confirmation per hash is permitted.
            e.HasIndex(t => t.TokenHash).IsUnique();
            e.Property(t => t.LoginProvider).HasMaxLength(64).IsRequired();
            e.Property(t => t.ProviderKey).HasMaxLength(256).IsRequired();
            e.Property(t => t.ProviderDisplayName).HasMaxLength(256);
            e.Property(t => t.Email).HasMaxLength(256).IsRequired();
            e.Property(t => t.ReturnUrl).HasMaxLength(512);
            e.HasOne(t => t.Account)
             .WithMany()
             .HasForeignKey(t => t.AccountId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        // World Configuration
        builder.Entity<World>(e =>
        {
            e.HasKey(w => w.Id);
            e.Property(w => w.Id).HasMaxLength(64);
            e.Property(w => w.Name).HasMaxLength(128);
        });

        // Region Configuration
        builder.Entity<Region>(e =>
        {
            e.HasKey(r => r.Id);
            e.Property(r => r.Id).HasMaxLength(64);
            e.Property(r => r.Name).HasMaxLength(128);
            e.Property(r => r.Type).HasConversion<string>();
            e.HasOne(r => r.World)
             .WithMany(w => w.Regions)
             .HasForeignKey(r => r.WorldId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        // RegionConnection Configuration
        builder.Entity<RegionConnection>(e =>
        {
            e.HasKey(rc => new { rc.FromRegionId, rc.ToRegionId });
            e.HasOne(rc => rc.FromRegion)
             .WithMany(r => r.Connections)
             .HasForeignKey(rc => rc.FromRegionId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(rc => rc.ToRegion)
             .WithMany()
             .HasForeignKey(rc => rc.ToRegionId)
             .OnDelete(DeleteBehavior.Restrict);
        });

        // Zone Configuration
        builder.Entity<Zone>(e =>
        {
            e.HasKey(z => z.Id);
            e.Property(z => z.Id).HasMaxLength(64);
            e.Property(z => z.Type).HasConversion<string>();
            e.Property(z => z.RescueFundTotal).HasDefaultValue(0L);
            e.HasOne(z => z.Region)
             .WithMany(r => r.Zones)
             .HasForeignKey(z => z.RegionId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<PlayerSession>(e =>
        {
            e.HasKey(s => s.Id);
            // Each connection can only have one session at a time
            e.HasIndex(s => s.ConnectionId).IsUnique();
            // A character can only have one active session at any given time
            e.HasIndex(s => s.CharacterId).IsUnique();
            e.Property(s => s.RegionId).HasMaxLength(64).IsRequired();
            e.Property(s => s.ZoneId).HasMaxLength(64).IsRequired(false);
            e.HasOne(s => s.Character)
             .WithMany()
             .HasForeignKey(s => s.CharacterId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(s => s.Region)
             .WithMany()
             .HasForeignKey(s => s.RegionId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(s => s.Zone)
             .WithMany(z => z.Sessions)
             .HasForeignKey(s => s.ZoneId)
             .IsRequired(false)
             .OnDelete(DeleteBehavior.SetNull);
        });

        builder.Entity<FoundrySubmission>(e =>
        {
            e.HasKey(s => s.Id);
            e.Property(s => s.Title).HasMaxLength(200);
            // jsonb is PostgreSQL-specific; fall back to plain text for SQLite (tests).
            if (Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true)
                e.Property(s => s.Payload).HasColumnType("TEXT");
            else
                e.Property(s => s.Payload).HasColumnType("jsonb");
            e.Property(s => s.ContentType).HasConversion<string>();
            e.Property(s => s.Status).HasConversion<string>();
            e.HasOne(s => s.Submitter)
             .WithMany()
             .HasForeignKey(s => s.SubmitterId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(s => s.Reviewer)
             .WithMany()
             .HasForeignKey(s => s.ReviewerId)
             .IsRequired(false)
             .OnDelete(DeleteBehavior.SetNull);
            e.Property(s => s.Description).HasMaxLength(2000);
            e.HasIndex(s => s.Status);
            e.HasIndex(s => s.ContentType);
            e.HasIndex(s => s.CreatedAt);
        });

        builder.Entity<FoundryNotification>(e =>
        {
            e.HasKey(n => n.Id);
            e.Property(n => n.Message).HasMaxLength(500);
            e.HasOne(n => n.Recipient)
             .WithMany()
             .HasForeignKey(n => n.RecipientId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(n => n.Submission)
             .WithMany()
             .HasForeignKey(n => n.SubmissionId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasIndex(n => new { n.RecipientId, n.IsRead });
        });

        builder.Entity<FoundryVote>(e =>
        {
            e.HasKey(v => v.Id);
            // One vote per player per submission.
            e.HasIndex(v => new { v.SubmissionId, v.VoterId }).IsUnique();
            e.HasOne(v => v.Submission)
             .WithMany(s => s.Votes)
             .HasForeignKey(v => v.SubmissionId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(v => v.Voter)
             .WithMany()
             .HasForeignKey(v => v.VoterId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<Announcement>(e =>
        {
            e.HasKey(a => a.Id);
            e.Property(a => a.Title).HasMaxLength(200);
            e.Property(a => a.Category).HasMaxLength(64);
            e.HasIndex(a => new { a.IsActive, a.PublishedAt });
        });

        builder.Entity<GlobalStat>(e =>
        {
            e.HasKey(g => g.Key);
            e.Property(g => g.Key).HasMaxLength(64);
        });

        builder.Entity<AdminAuditEntry>(e =>
        {
            e.HasKey(a => a.Id);
            e.Property(a => a.Action).HasMaxLength(64).IsRequired();
            e.Property(a => a.ActorUsername).HasMaxLength(256).IsRequired();
            e.Property(a => a.TargetUsername).HasMaxLength(256).IsRequired(false);
            e.Property(a => a.Details).HasMaxLength(1000).IsRequired(false);
            e.HasIndex(a => a.ActorAccountId);
            e.HasIndex(a => a.TargetAccountId);
            e.HasIndex(a => a.OccurredAt);
        });

        builder.Entity<PlayerReport>(e =>
        {
            e.HasKey(r => r.Id);
            e.Property(r => r.ReporterName).HasMaxLength(64).IsRequired();
            e.Property(r => r.TargetName).HasMaxLength(64).IsRequired();
            e.Property(r => r.Reason).HasMaxLength(1000).IsRequired();
            e.HasIndex(r => r.IsResolved);
            e.HasIndex(r => r.SubmittedAt);
            e.HasIndex(r => r.TargetCharacterId);
        });

        // SQLite cannot translate ORDER BY on DateTimeOffset columns; store as ISO 8601 text
        // so comparisons and ORDER BY work correctly in the SQLite test environment.
        // This block is skipped for PostgreSQL (production) where DateTimeOffset is native.
        if (Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true)
        {
            var converter = new DateTimeOffsetToStringConverter();
            foreach (var entityType in builder.Model.GetEntityTypes())
            {
                foreach (var property in entityType.GetProperties()
                    .Where(p => p.ClrType == typeof(DateTimeOffset) || p.ClrType == typeof(DateTimeOffset?)))
                {
                    property.SetValueConverter(converter);
                }
            }
        }
    }
}
