using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealmEngine.Data.Entities;
using RealmUnbound.Server.Data.Entities;

namespace RealmUnbound.Server.Data;

/// <summary>
/// Primary EF Core context for all server-side persistence.
/// Inherits ASP.NET Core Identity tables (AspNetUsers, AspNetRoles, etc.) via
/// <see cref="IdentityDbContext{TUser,TRole,TKey}"/>.
/// Always backed by PostgreSQL; use <see cref="ContentDbContext"/> for standalone
/// content-browsing tools (e.g. RealmForge) that don't need Identity.
/// </summary>
public class ApplicationDbContext : IdentityDbContext<PlayerAccount, IdentityRole<Guid>, Guid>
{
    /// <summary>Initializes a new instance of <see cref="ApplicationDbContext"/>.</summary>
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }

    /// <summary>Game characters owned by player accounts.</summary>
    public DbSet<Entities.Character> Characters => Set<Entities.Character>();
    /// <summary>JWT refresh tokens.</summary>
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    /// <summary>Top-level world containers (currently only Draveth).</summary>
    public DbSet<World> Worlds => Set<World>();
    /// <summary>Geographic regions within a world.</summary>
    public DbSet<Region> Regions => Set<Region>();
    /// <summary>Directed travel edges between adjacent regions.</summary>
    public DbSet<RegionConnection> RegionConnections => Set<RegionConnection>();
    /// <summary>Zone catalog — static and procedurally generated areas.</summary>
    public DbSet<Zone> Zones => Set<Zone>();
    /// <summary>Directed travel edges between adjacent zones.</summary>
    public DbSet<ZoneConnection> ZoneConnections => Set<ZoneConnection>();
    /// <summary>Live records of characters currently inside a zone.</summary>
    public DbSet<ZoneSession> ZoneSessions => Set<ZoneSession>();
    /// <summary>Community content submissions for the Foundry portal.</summary>
    public DbSet<FoundrySubmission> FoundrySubmissions => Set<FoundrySubmission>();
    /// <summary>User votes on Foundry submissions.</summary>
    public DbSet<FoundryVote> FoundryVotes => Set<FoundryVote>();
    /// <summary>User notifications generated by Foundry review events.</summary>
    public DbSet<FoundryNotification> FoundryNotifications => Set<FoundryNotification>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder); // required — scaffolds all Identity tables

        builder.Entity<Entities.Character>(e =>
        {
            e.HasKey(c => c.Id);
            // Character names are globally unique across the server.
            e.HasIndex(c => c.Name).IsUnique();
            // A single account cannot have two characters in the same slot.
            e.HasIndex(c => new { c.AccountId, c.SlotIndex }).IsUnique();
            e.Property(c => c.Attributes).HasColumnType("text");
            e.Property(c => c.EquipmentBlob).HasColumnType("text").HasDefaultValue("{}");
            e.HasOne(c => c.Account)
             .WithMany()
             .HasForeignKey(c => c.AccountId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<RefreshToken>(e =>
        {
            e.HasKey(rt => rt.Id);
            e.HasIndex(rt => rt.TokenHash).IsUnique();
            e.HasOne(rt => rt.Account)
             .WithMany()
             .HasForeignKey(rt => rt.AccountId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        // ─ World Configuration ─
        builder.Entity<World>(e =>
        {
            e.HasKey(w => w.Id);
            e.Property(w => w.Id).HasMaxLength(64);
            e.Property(w => w.Name).HasMaxLength(128);
            e.HasData(
                new World
                {
                    Id          = "draveth",
                    Name        = "Draveth",
                    Description = "A world of scattered kingdoms, ancient ruins, and contested wilds, shaped by centuries of war and forgotten magic.",
                    Era         = "The Age of Embers",
                }
            );
        });

        // ─ Region Configuration ─
        builder.Entity<Region>(e =>
        {
            e.HasKey(r => r.Id);
            e.Property(r => r.Id).HasMaxLength(64);
            e.Property(r => r.Name).HasMaxLength(128);
            e.Property(r => r.Type).HasConversion<string>();
            e.HasOne(r => r.World)
             .WithMany(w => w.Regions)
             .HasForeignKey(r => r.WorldId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasData(
                new Region { Id = "thornveil",   Name = "Thornveil",   Description = "A dense Eiraveth forest shrouding ruins of the first kingdoms, where moss-covered paths lead beginners into adventure.", Type = RegionType.Forest,   MinLevel = 0,  MaxLevel = 6,  IsStarter = true,  IsDiscoverable = true, WorldId = "draveth" },
                new Region { Id = "greymoor",    Name = "Greymoor",    Description = "Fog-wreathed Dravan highlands where ancient burial mounds dot the heather and wandering spirits trouble the living.",    Type = RegionType.Highland, MinLevel = 5,  MaxLevel = 14, IsStarter = false, IsDiscoverable = true, WorldId = "draveth" },
                new Region { Id = "saltcliff",   Name = "Saltcliff",   Description = "Thysmara sea cliffs battered by storm winds, home to sailors, smugglers, and the drowned remnants of a sunken empire.",  Type = RegionType.Coastal,  MinLevel = 10, MaxLevel = 20, IsStarter = false, IsDiscoverable = true, WorldId = "draveth" },
                new Region { Id = "cinderplain", Name = "Cinderplain", Description = "Kaldrek's scorched expanse of ash and cooled lava, where forge-tempered warbands and fire-touched creatures stake their claim.", Type = RegionType.Volcanic, MinLevel = 18, MaxLevel = 30, IsStarter = false, IsDiscoverable = true, WorldId = "draveth" }
            );
        });

        // ─ RegionConnection Configuration ─
        builder.Entity<RegionConnection>(e =>
        {
            e.HasKey(rc => new { rc.FromRegionId, rc.ToRegionId });
            e.HasOne(rc => rc.FromRegion)
             .WithMany(r => r.Connections)
             .HasForeignKey(rc => rc.FromRegionId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(rc => rc.ToRegion)
             .WithMany()
             .HasForeignKey(rc => rc.ToRegionId)
             .OnDelete(DeleteBehavior.Restrict);
            // Bidirectional: each pair needs two rows (A→B and B→A).
            e.HasData(
                new RegionConnection { FromRegionId = "thornveil",   ToRegionId = "greymoor"    },
                new RegionConnection { FromRegionId = "greymoor",    ToRegionId = "thornveil"   },
                new RegionConnection { FromRegionId = "greymoor",    ToRegionId = "saltcliff"   },
                new RegionConnection { FromRegionId = "saltcliff",   ToRegionId = "greymoor"    },
                new RegionConnection { FromRegionId = "greymoor",    ToRegionId = "cinderplain" },
                new RegionConnection { FromRegionId = "cinderplain", ToRegionId = "greymoor"    }
            );
        });

        // ─ Zone Configuration ─
        builder.Entity<Zone>(e =>
        {
            e.HasKey(z => z.Id);
            e.Property(z => z.Id).HasMaxLength(64);
            e.Property(z => z.Type).HasConversion<string>();
            e.HasOne(z => z.Region)
             .WithMany(r => r.Zones)
             .HasForeignKey(z => z.RegionId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasMany(z => z.Sessions)
             .WithOne(s => s.Zone)
             .HasForeignKey(s => s.ZoneId)
             .OnDelete(DeleteBehavior.Cascade);

            // Static zone seed — 16 zones across 4 regions of Draveth.
            e.HasData(
                // ── Thornveil ──────────────────────────────────────────────────────────
                new Zone { Id = "fenwick-crossing",  Name = "Fenwick's Crossing",    Description = "A well-worn crossroads inn and market at the forest's edge, where new adventurers take their first uncertain steps.",              Type = ZoneType.Town,       MinLevel = 0,  MaxPlayers = 0, IsStarter = true,  HasInn = true,  HasMerchant = true,  IsPvpEnabled = false, IsDiscoverable = true, RegionId = "thornveil"   },
                new Zone { Id = "greenveil-paths",   Name = "The Greenveil Paths",   Description = "Winding root-bound trails beneath a canopy of ancient oaks, alive with sprites and overly curious wildlife.",                    Type = ZoneType.Wilderness, MinLevel = 1,  MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "thornveil"   },
                new Zone { Id = "thornveil-hollow",  Name = "Thornveil Hollow",      Description = "A shaded hollow deep in the forest where old Eiraveth wards have begun to fail and darker things stir.",                         Type = ZoneType.Wilderness, MinLevel = 3,  MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "thornveil"   },
                new Zone { Id = "verdant-barrow",    Name = "The Verdant Barrow",    Description = "A barrow complex reclaimed by roots and bioluminescent fungi, prowled by the restless dead of a forgotten village.",              Type = ZoneType.Dungeon,    MinLevel = 4,  MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "thornveil"   },
                // ── Greymoor ───────────────────────────────────────────────────────────
                new Zone { Id = "aldenmere",         Name = "Aldenmere",             Description = "A grey-stoned Dravan waytown built atop old foundations, known for its mead, its mercenaries, and its many secrets.",             Type = ZoneType.Town,       MinLevel = 5,  MaxPlayers = 0, IsStarter = false, HasInn = true,  HasMerchant = true,  IsPvpEnabled = false, IsDiscoverable = true, RegionId = "greymoor"    },
                new Zone { Id = "pale-moor",         Name = "The Pale Moor",         Description = "Endless fog-blanketed moors where waymarks shift overnight and travellers learn quickly to trust local guides.",                   Type = ZoneType.Wilderness, MinLevel = 7,  MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "greymoor"    },
                new Zone { Id = "soddenfen",         Name = "Soddenfen",             Description = "A waterlogged fenland buzzing with plague insects and half-submerged ruins, avoided by all with good sense.",                     Type = ZoneType.Wilderness, MinLevel = 9,  MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "greymoor"    },
                new Zone { Id = "barrow-deeps",      Name = "The Barrow Deeps",      Description = "A sprawling underground burial network carved through the moorland, where ancestor-beasts guard ancient Dravan relics.",           Type = ZoneType.Dungeon,    MinLevel = 11, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "greymoor"    },
                // ── Saltcliff ──────────────────────────────────────────────────────────
                new Zone { Id = "tolvaren",          Name = "Tolvaren",              Description = "A salt-caked Thysmara port city clinging to the cliff face, its harbour full of storm-worn ships and bold-faced traders.",         Type = ZoneType.Town,       MinLevel = 10, MaxPlayers = 0, IsStarter = false, HasInn = true,  HasMerchant = true,  IsPvpEnabled = false, IsDiscoverable = true, RegionId = "saltcliff"   },
                new Zone { Id = "tidewrack-flats",   Name = "The Tidewrack Flats",   Description = "Tide-scoured mudflats littered with shipwreck timber and kelp-draped bones, hunted by scavengers and wading predators.",          Type = ZoneType.Wilderness, MinLevel = 12, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "saltcliff"   },
                new Zone { Id = "saltcliff-heights", Name = "The Saltcliff Heights", Description = "Wind-blasted clifftops above the Thysmara sea, dotted with lighthouse ruins and contested by rival gull-rider clans.",            Type = ZoneType.Wilderness, MinLevel = 14, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "saltcliff"   },
                new Zone { Id = "sunken-name",       Name = "The Sunken Name",       Description = "The drowned heart of a once-great Thysmara empire, now a flooded ruin accessible only to the brave and the waterproofed.",         Type = ZoneType.Dungeon,    MinLevel = 16, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "saltcliff"   },
                // ── Cinderplain ────────────────────────────────────────────────────────
                new Zone { Id = "skarhold",          Name = "Skarhold",              Description = "A Kaldrek forge-city built inside a dormant caldera, where the best smiths in Draveth ply their trade under sulphur skies.",      Type = ZoneType.Town,       MinLevel = 18, MaxPlayers = 0, IsStarter = false, HasInn = true,  HasMerchant = true,  IsPvpEnabled = false, IsDiscoverable = true, RegionId = "cinderplain" },
                new Zone { Id = "ashfields",         Name = "The Ashfields",         Description = "Grey ash plains stretching to the horizon, dotted with fused obsidian trees and the scorched skulls of fallen armies.",            Type = ZoneType.Wilderness, MinLevel = 20, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "cinderplain" },
                new Zone { Id = "smoldering-reach",  Name = "The Smoldering Reach",  Description = "A cracked lava field where vents of superheated gas erupt without warning and heat-adapted predators hunt at dusk.",               Type = ZoneType.Wilderness, MinLevel = 23, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "cinderplain" },
                new Zone { Id = "kaldrek-maw",       Name = "Kaldrek's Maw",         Description = "A vast volcanic vent complex known as the Maw, lair of Kaldrek's fire-bound ancient and final test of the worthy.",               Type = ZoneType.Dungeon,    MinLevel = 26, MaxPlayers = 0, IsStarter = false, HasInn = false, HasMerchant = false, IsPvpEnabled = false, IsDiscoverable = true, RegionId = "cinderplain" }
            );
        });

        // ─ ZoneConnection Configuration ─
        builder.Entity<ZoneConnection>(e =>
        {
            e.HasKey(zc => new { zc.FromZoneId, zc.ToZoneId });
            e.HasOne(zc => zc.FromZone)
             .WithMany(z => z.Exits)
             .HasForeignKey(zc => zc.FromZoneId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(zc => zc.ToZone)
             .WithMany()
             .HasForeignKey(zc => zc.ToZoneId)
             .OnDelete(DeleteBehavior.Restrict);
            // Bidirectional: each pair needs two rows (A→B and B→A).
            e.HasData(
                // ── Thornveil internal ─────────────────────────────────────────────────
                new ZoneConnection { FromZoneId = "fenwick-crossing",  ToZoneId = "greenveil-paths"  },
                new ZoneConnection { FromZoneId = "greenveil-paths",   ToZoneId = "fenwick-crossing" },
                new ZoneConnection { FromZoneId = "greenveil-paths",   ToZoneId = "thornveil-hollow" },
                new ZoneConnection { FromZoneId = "thornveil-hollow",  ToZoneId = "greenveil-paths"  },
                new ZoneConnection { FromZoneId = "thornveil-hollow",  ToZoneId = "verdant-barrow"   },
                new ZoneConnection { FromZoneId = "verdant-barrow",    ToZoneId = "thornveil-hollow" },
                // ── Thornveil → Greymoor border ────────────────────────────────────────
                new ZoneConnection { FromZoneId = "thornveil-hollow",  ToZoneId = "aldenmere"        },
                new ZoneConnection { FromZoneId = "aldenmere",         ToZoneId = "thornveil-hollow" },
                // ── Greymoor internal ──────────────────────────────────────────────────
                new ZoneConnection { FromZoneId = "aldenmere",         ToZoneId = "pale-moor"        },
                new ZoneConnection { FromZoneId = "pale-moor",         ToZoneId = "aldenmere"        },
                new ZoneConnection { FromZoneId = "pale-moor",         ToZoneId = "soddenfen"        },
                new ZoneConnection { FromZoneId = "soddenfen",         ToZoneId = "pale-moor"        },
                new ZoneConnection { FromZoneId = "soddenfen",         ToZoneId = "barrow-deeps"     },
                new ZoneConnection { FromZoneId = "barrow-deeps",      ToZoneId = "soddenfen"        },
                // ── Greymoor → Saltcliff border ────────────────────────────────────────
                new ZoneConnection { FromZoneId = "soddenfen",         ToZoneId = "tolvaren"         },
                new ZoneConnection { FromZoneId = "tolvaren",          ToZoneId = "soddenfen"        },
                // ── Saltcliff internal ─────────────────────────────────────────────────
                new ZoneConnection { FromZoneId = "tolvaren",          ToZoneId = "tidewrack-flats"  },
                new ZoneConnection { FromZoneId = "tidewrack-flats",   ToZoneId = "tolvaren"         },
                new ZoneConnection { FromZoneId = "tidewrack-flats",   ToZoneId = "saltcliff-heights"},
                new ZoneConnection { FromZoneId = "saltcliff-heights", ToZoneId = "tidewrack-flats"  },
                new ZoneConnection { FromZoneId = "saltcliff-heights", ToZoneId = "sunken-name"      },
                new ZoneConnection { FromZoneId = "sunken-name",       ToZoneId = "saltcliff-heights"},
                // ── Greymoor → Cinderplain border ──────────────────────────────────────
                new ZoneConnection { FromZoneId = "barrow-deeps",      ToZoneId = "skarhold"         },
                new ZoneConnection { FromZoneId = "skarhold",          ToZoneId = "barrow-deeps"     },
                // ── Cinderplain internal ───────────────────────────────────────────────
                new ZoneConnection { FromZoneId = "skarhold",          ToZoneId = "ashfields"        },
                new ZoneConnection { FromZoneId = "ashfields",         ToZoneId = "skarhold"         },
                new ZoneConnection { FromZoneId = "ashfields",         ToZoneId = "smoldering-reach" },
                new ZoneConnection { FromZoneId = "smoldering-reach",  ToZoneId = "ashfields"        },
                new ZoneConnection { FromZoneId = "smoldering-reach",  ToZoneId = "kaldrek-maw"      },
                new ZoneConnection { FromZoneId = "kaldrek-maw",       ToZoneId = "smoldering-reach" }
            );
        });

        builder.Entity<ZoneSession>(e =>
        {
            e.HasKey(s => s.Id);
            // Each connection can only be in one zone at a time
            e.HasIndex(s => s.ConnectionId).IsUnique();
            // A character can only be in one zone session at any given time
            e.HasIndex(s => s.CharacterId).IsUnique();
            e.HasOne(s => s.Character)
             .WithMany()
             .HasForeignKey(s => s.CharacterId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        builder.Entity<FoundrySubmission>(e =>
        {
            e.HasKey(s => s.Id);
            e.Property(s => s.Title).HasMaxLength(200);
            // jsonb is PostgreSQL-specific; fall back to plain text for SQLite (tests).
            if (Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true)
                e.Property(s => s.Payload).HasColumnType("TEXT");
            else
                e.Property(s => s.Payload).HasColumnType("jsonb");
            e.Property(s => s.ContentType).HasConversion<string>();
            e.Property(s => s.Status).HasConversion<string>();
            e.HasOne(s => s.Submitter)
             .WithMany()
             .HasForeignKey(s => s.SubmitterId)
             .OnDelete(DeleteBehavior.Restrict);
            e.HasOne(s => s.Reviewer)
             .WithMany()
             .HasForeignKey(s => s.ReviewerId)
             .IsRequired(false)
             .OnDelete(DeleteBehavior.SetNull);
            e.Property(s => s.Description).HasMaxLength(2000);
            e.HasIndex(s => s.Status);
            e.HasIndex(s => s.ContentType);
            e.HasIndex(s => s.CreatedAt);
        });

        builder.Entity<FoundryNotification>(e =>
        {
            e.HasKey(n => n.Id);
            e.Property(n => n.Message).HasMaxLength(500);
            e.HasOne(n => n.Recipient)
             .WithMany()
             .HasForeignKey(n => n.RecipientId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(n => n.Submission)
             .WithMany()
             .HasForeignKey(n => n.SubmissionId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasIndex(n => new { n.RecipientId, n.IsRead });
        });

        builder.Entity<FoundryVote>(e =>
        {
            e.HasKey(v => v.Id);
            // One vote per player per submission.
            e.HasIndex(v => new { v.SubmissionId, v.VoterId }).IsUnique();
            e.HasOne(v => v.Submission)
             .WithMany(s => s.Votes)
             .HasForeignKey(v => v.SubmissionId)
             .OnDelete(DeleteBehavior.Cascade);
            e.HasOne(v => v.Voter)
             .WithMany()
             .HasForeignKey(v => v.VoterId)
             .OnDelete(DeleteBehavior.Cascade);
        });

        // SQLite cannot translate ORDER BY on DateTimeOffset columns; store as ISO 8601 text
        // so comparisons and ORDER BY work correctly in the SQLite test environment.
        // This block is skipped for PostgreSQL (production) where DateTimeOffset is native.
        if (Database.ProviderName?.Contains("Sqlite", StringComparison.OrdinalIgnoreCase) == true)
        {
            var converter = new DateTimeOffsetToStringConverter();
            foreach (var entityType in builder.Model.GetEntityTypes())
            {
                foreach (var property in entityType.GetProperties()
                    .Where(p => p.ClrType == typeof(DateTimeOffset) || p.ClrType == typeof(DateTimeOffset?)))
                {
                    property.SetValueConverter(converter);
                }
            }
        }
    }
}
