// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealmUnbound.Server.Data;

#nullable disable

namespace RealmUnbound.Server.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321151634_AddWorldRegionZoneConnections")]
    partial class AddWorldRegionZoneConnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentBlob")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastPlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<string>("StartingZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("AccountId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundryNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("RecipientId", "IsRead");

                    b.ToTable("FoundryNotifications");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundrySubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmitterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmitterId");

                    b.ToTable("FoundrySubmissions");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundryVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VoterId");

                    b.HasIndex("SubmissionId", "VoterId")
                        .IsUnique();

                    b.ToTable("FoundryVotes");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.PlayerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxCharacterSlots")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Region", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = "thornveil",
                            Description = "A dense Eiraveth forest shrouding ruins of the first kingdoms, where moss-covered paths lead beginners into adventure.",
                            IsDiscoverable = true,
                            IsStarter = true,
                            MaxLevel = 6,
                            MinLevel = 0,
                            Name = "Thornveil",
                            Type = "Forest",
                            WorldId = "draveth"
                        },
                        new
                        {
                            Id = "greymoor",
                            Description = "Fog-wreathed Dravan highlands where ancient burial mounds dot the heather and wandering spirits trouble the living.",
                            IsDiscoverable = true,
                            IsStarter = false,
                            MaxLevel = 14,
                            MinLevel = 5,
                            Name = "Greymoor",
                            Type = "Highland",
                            WorldId = "draveth"
                        },
                        new
                        {
                            Id = "saltcliff",
                            Description = "Thysmara sea cliffs battered by storm winds, home to sailors, smugglers, and the drowned remnants of a sunken empire.",
                            IsDiscoverable = true,
                            IsStarter = false,
                            MaxLevel = 20,
                            MinLevel = 10,
                            Name = "Saltcliff",
                            Type = "Coastal",
                            WorldId = "draveth"
                        },
                        new
                        {
                            Id = "cinderplain",
                            Description = "Kaldrek's scorched expanse of ash and cooled lava, where forge-tempered warbands and fire-touched creatures stake their claim.",
                            IsDiscoverable = true,
                            IsStarter = false,
                            MaxLevel = 30,
                            MinLevel = 18,
                            Name = "Cinderplain",
                            Type = "Volcanic",
                            WorldId = "draveth"
                        });
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.RegionConnection", b =>
                {
                    b.Property<string>("FromRegionId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToRegionId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("FromRegionId", "ToRegionId");

                    b.HasIndex("ToRegionId");

                    b.ToTable("RegionConnections");

                    b.HasData(
                        new
                        {
                            FromRegionId = "thornveil",
                            ToRegionId = "greymoor"
                        },
                        new
                        {
                            FromRegionId = "greymoor",
                            ToRegionId = "thornveil"
                        },
                        new
                        {
                            FromRegionId = "greymoor",
                            ToRegionId = "saltcliff"
                        },
                        new
                        {
                            FromRegionId = "saltcliff",
                            ToRegionId = "greymoor"
                        },
                        new
                        {
                            FromRegionId = "greymoor",
                            ToRegionId = "cinderplain"
                        },
                        new
                        {
                            FromRegionId = "cinderplain",
                            ToRegionId = "greymoor"
                        });
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.World", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Era")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Worlds");

                    b.HasData(
                        new
                        {
                            Id = "draveth",
                            Description = "A world of scattered kingdoms, ancient ruins, and contested wilds, shaped by centuries of war and forgotten magic.",
                            Era = "The Age of Embers",
                            Name = "Draveth"
                        });
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Zone", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasInn")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMerchant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDiscoverable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPvpEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = "fenwick-crossing",
                            Description = "A well-worn crossroads inn and market at the forest's edge, where new adventurers take their first uncertain steps.",
                            HasInn = true,
                            HasMerchant = true,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = true,
                            MaxPlayers = 0,
                            MinLevel = 0,
                            Name = "Fenwick's Crossing",
                            RegionId = "thornveil",
                            Type = "Town"
                        },
                        new
                        {
                            Id = "greenveil-paths",
                            Description = "Winding root-bound trails beneath a canopy of ancient oaks, alive with sprites and overly curious wildlife.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 1,
                            Name = "The Greenveil Paths",
                            RegionId = "thornveil",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "thornveil-hollow",
                            Description = "A shaded hollow deep in the forest where old Eiraveth wards have begun to fail and darker things stir.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 3,
                            Name = "Thornveil Hollow",
                            RegionId = "thornveil",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "verdant-barrow",
                            Description = "A barrow complex reclaimed by roots and bioluminescent fungi, prowled by the restless dead of a forgotten village.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 4,
                            Name = "The Verdant Barrow",
                            RegionId = "thornveil",
                            Type = "Dungeon"
                        },
                        new
                        {
                            Id = "aldenmere",
                            Description = "A grey-stoned Dravan waytown built atop old foundations, known for its mead, its mercenaries, and its many secrets.",
                            HasInn = true,
                            HasMerchant = true,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 5,
                            Name = "Aldenmere",
                            RegionId = "greymoor",
                            Type = "Town"
                        },
                        new
                        {
                            Id = "pale-moor",
                            Description = "Endless fog-blanketed moors where waymarks shift overnight and travellers learn quickly to trust local guides.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 7,
                            Name = "The Pale Moor",
                            RegionId = "greymoor",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "soddenfen",
                            Description = "A waterlogged fenland buzzing with plague insects and half-submerged ruins, avoided by all with good sense.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 9,
                            Name = "Soddenfen",
                            RegionId = "greymoor",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "barrow-deeps",
                            Description = "A sprawling underground burial network carved through the moorland, where ancestor-beasts guard ancient Dravan relics.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 11,
                            Name = "The Barrow Deeps",
                            RegionId = "greymoor",
                            Type = "Dungeon"
                        },
                        new
                        {
                            Id = "tolvaren",
                            Description = "A salt-caked Thysmara port city clinging to the cliff face, its harbour full of storm-worn ships and bold-faced traders.",
                            HasInn = true,
                            HasMerchant = true,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 10,
                            Name = "Tolvaren",
                            RegionId = "saltcliff",
                            Type = "Town"
                        },
                        new
                        {
                            Id = "tidewrack-flats",
                            Description = "Tide-scoured mudflats littered with shipwreck timber and kelp-draped bones, hunted by scavengers and wading predators.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 12,
                            Name = "The Tidewrack Flats",
                            RegionId = "saltcliff",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "saltcliff-heights",
                            Description = "Wind-blasted clifftops above the Thysmara sea, dotted with lighthouse ruins and contested by rival gull-rider clans.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 14,
                            Name = "The Saltcliff Heights",
                            RegionId = "saltcliff",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "sunken-name",
                            Description = "The drowned heart of a once-great Thysmara empire, now a flooded ruin accessible only to the brave and the waterproofed.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 16,
                            Name = "The Sunken Name",
                            RegionId = "saltcliff",
                            Type = "Dungeon"
                        },
                        new
                        {
                            Id = "skarhold",
                            Description = "A Kaldrek forge-city built inside a dormant caldera, where the best smiths in Draveth ply their trade under sulphur skies.",
                            HasInn = true,
                            HasMerchant = true,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 18,
                            Name = "Skarhold",
                            RegionId = "cinderplain",
                            Type = "Town"
                        },
                        new
                        {
                            Id = "ashfields",
                            Description = "Grey ash plains stretching to the horizon, dotted with fused obsidian trees and the scorched skulls of fallen armies.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 20,
                            Name = "The Ashfields",
                            RegionId = "cinderplain",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "smoldering-reach",
                            Description = "A cracked lava field where vents of superheated gas erupt without warning and heat-adapted predators hunt at dusk.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 23,
                            Name = "The Smoldering Reach",
                            RegionId = "cinderplain",
                            Type = "Wilderness"
                        },
                        new
                        {
                            Id = "kaldrek-maw",
                            Description = "A vast volcanic vent complex known as the Maw, lair of Kaldrek's fire-bound ancient and final test of the worthy.",
                            HasInn = false,
                            HasMerchant = false,
                            IsDiscoverable = true,
                            IsPvpEnabled = false,
                            IsStarter = false,
                            MaxPlayers = 0,
                            MinLevel = 26,
                            Name = "Kaldrek's Maw",
                            RegionId = "cinderplain",
                            Type = "Dungeon"
                        });
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.ZoneConnection", b =>
                {
                    b.Property<string>("FromZoneId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ToZoneId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("FromZoneId", "ToZoneId");

                    b.HasIndex("ToZoneId");

                    b.ToTable("ZoneConnections");

                    b.HasData(
                        new
                        {
                            FromZoneId = "fenwick-crossing",
                            ToZoneId = "greenveil-paths"
                        },
                        new
                        {
                            FromZoneId = "greenveil-paths",
                            ToZoneId = "fenwick-crossing"
                        },
                        new
                        {
                            FromZoneId = "greenveil-paths",
                            ToZoneId = "thornveil-hollow"
                        },
                        new
                        {
                            FromZoneId = "thornveil-hollow",
                            ToZoneId = "greenveil-paths"
                        },
                        new
                        {
                            FromZoneId = "thornveil-hollow",
                            ToZoneId = "verdant-barrow"
                        },
                        new
                        {
                            FromZoneId = "verdant-barrow",
                            ToZoneId = "thornveil-hollow"
                        },
                        new
                        {
                            FromZoneId = "thornveil-hollow",
                            ToZoneId = "aldenmere"
                        },
                        new
                        {
                            FromZoneId = "aldenmere",
                            ToZoneId = "thornveil-hollow"
                        },
                        new
                        {
                            FromZoneId = "aldenmere",
                            ToZoneId = "pale-moor"
                        },
                        new
                        {
                            FromZoneId = "pale-moor",
                            ToZoneId = "aldenmere"
                        },
                        new
                        {
                            FromZoneId = "pale-moor",
                            ToZoneId = "soddenfen"
                        },
                        new
                        {
                            FromZoneId = "soddenfen",
                            ToZoneId = "pale-moor"
                        },
                        new
                        {
                            FromZoneId = "soddenfen",
                            ToZoneId = "barrow-deeps"
                        },
                        new
                        {
                            FromZoneId = "barrow-deeps",
                            ToZoneId = "soddenfen"
                        },
                        new
                        {
                            FromZoneId = "soddenfen",
                            ToZoneId = "tolvaren"
                        },
                        new
                        {
                            FromZoneId = "tolvaren",
                            ToZoneId = "soddenfen"
                        },
                        new
                        {
                            FromZoneId = "tolvaren",
                            ToZoneId = "tidewrack-flats"
                        },
                        new
                        {
                            FromZoneId = "tidewrack-flats",
                            ToZoneId = "tolvaren"
                        },
                        new
                        {
                            FromZoneId = "tidewrack-flats",
                            ToZoneId = "saltcliff-heights"
                        },
                        new
                        {
                            FromZoneId = "saltcliff-heights",
                            ToZoneId = "tidewrack-flats"
                        },
                        new
                        {
                            FromZoneId = "saltcliff-heights",
                            ToZoneId = "sunken-name"
                        },
                        new
                        {
                            FromZoneId = "sunken-name",
                            ToZoneId = "saltcliff-heights"
                        },
                        new
                        {
                            FromZoneId = "barrow-deeps",
                            ToZoneId = "skarhold"
                        },
                        new
                        {
                            FromZoneId = "skarhold",
                            ToZoneId = "barrow-deeps"
                        },
                        new
                        {
                            FromZoneId = "skarhold",
                            ToZoneId = "ashfields"
                        },
                        new
                        {
                            FromZoneId = "ashfields",
                            ToZoneId = "skarhold"
                        },
                        new
                        {
                            FromZoneId = "ashfields",
                            ToZoneId = "smoldering-reach"
                        },
                        new
                        {
                            FromZoneId = "smoldering-reach",
                            ToZoneId = "ashfields"
                        },
                        new
                        {
                            FromZoneId = "smoldering-reach",
                            ToZoneId = "kaldrek-maw"
                        },
                        new
                        {
                            FromZoneId = "kaldrek-maw",
                            ToZoneId = "smoldering-reach"
                        });
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.ZoneSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Character", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundryNotification", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.FoundrySubmission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundrySubmission", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundryVote", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.FoundrySubmission", "Submission")
                        .WithMany("Votes")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Voter")
                        .WithMany()
                        .HasForeignKey("VoterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("Voter");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.PlayerAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Region", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.World", "World")
                        .WithMany("Regions")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.RegionConnection", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.Region", "FromRegion")
                        .WithMany("Connections")
                        .HasForeignKey("FromRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.Region", "ToRegion")
                        .WithMany()
                        .HasForeignKey("ToRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRegion");

                    b.Navigation("ToRegion");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Zone", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.Region", "Region")
                        .WithMany("Zones")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.ZoneConnection", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.Zone", "FromZone")
                        .WithMany("Exits")
                        .HasForeignKey("FromZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.Zone", "ToZone")
                        .WithMany()
                        .HasForeignKey("ToZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromZone");

                    b.Navigation("ToZone");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.ZoneSession", b =>
                {
                    b.HasOne("RealmUnbound.Server.Data.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealmUnbound.Server.Data.Entities.Zone", "Zone")
                        .WithMany("Sessions")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.FoundrySubmission", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Region", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.World", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("RealmUnbound.Server.Data.Entities.Zone", b =>
                {
                    b.Navigation("Exits");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
