// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RealmEngine.Data.Persistence;

#nullable disable

namespace RealmEngine.Data.Migrations.GameDb
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260319032137_AddInventoryRecordDurability")]
    partial class AddInventoryRecordDurability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RealmEngine.Data.Persistence.InventoryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Durability")
                        .HasColumnType("integer");

                    b.Property<string>("ItemRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SaveGameId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SaveGameId", "CharacterName");

                    b.HasIndex("SaveGameId", "CharacterName", "ItemRef")
                        .IsUnique();

                    b.ToTable("InventoryRecords");
                });

            modelBuilder.Entity("RealmEngine.Data.Persistence.SaveGameRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.HasIndex("SlotIndex");

                    b.ToTable("SaveGames");
                });

            modelBuilder.Entity("RealmEngine.Shared.Models.HallOfFameEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AchievementsUnlocked")
                        .HasColumnType("integer");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DeathDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeathLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeathReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FameScore")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPermadeath")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PlayTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("QuestsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEnemiesDefeated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FameScore");

                    b.ToTable("HallOfFameEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
